name: LideWear
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.7.0
  webview_flutter_android: ^3.16.0
  webview_flutter_wkwebview: ^3.12.0
  provider: ^6.1.1
  http: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.2.5
  cupertino_icons: ^1.0.8
  app_links: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/lidewear_logo.png # full logo with text
    - assets/images/lidewear_icon.png # monogram LW (no text)

# ----------------------------
# 🚀 App Icon Configuration
# ----------------------------
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/lidewear_icon.png" # clean "LW" version
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/lidewear_icon.png"

# ----------------------------
# 🚀 Splash Screen Configuration
# ----------------------------
flutter_native_splash:
  color: "#000000" # black background
  image: assets/images/lidewear_logo.png # full logo centered
  android: true
  ios: true
  web: false
  fullscreen: true # ✅ make the logo take up more space
